-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.users
(
    id integer NOT NULL,
    email character varying(50) NOT NULL,
    password character varying(100) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.candidates
(
    user_id integer NOT NULL,
    first_name character varying(30) NOT NULL,
    last_name character varying(30) NOT NULL,
    nationality_id character varying(11) NOT NULL,
    birth_of_date date NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.employers
(
    user_id integer NOT NULL,
    company_name character varying(200) NOT NULL,
    web_address character varying(50) NOT NULL,
    phone_number character varying(50) NOT NULL,
    tax_number character varying(50) NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.system_personels
(
    user_id integer NOT NULL,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    nationality_id character varying(11) NOT NULL,
    birth_of_date date NOT NULL,
    personel_number character varying(50) NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.job_positions
(
    id integer NOT NULL,
    job_position character varying(100) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.activation_codes
(
    id integer NOT NULL,
    activation_code character varying(50) NOT NULL,
    is_used boolean NOT NULL,
    confirmed_date date NOT NULL,
    user_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.confirmation
(
    id integer NOT NULL,
    system_personel_id integer NOT NULL,
    employer_id integer NOT NULL,
    is_confirmed boolean NOT NULL,
    confirmed_date date NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE public.users
    ADD FOREIGN KEY (id)
    REFERENCES public.system_personels (user_id)
    NOT VALID;


ALTER TABLE public.users
    ADD FOREIGN KEY (id)
    REFERENCES public.employers (user_id)
    NOT VALID;


ALTER TABLE public.users
    ADD FOREIGN KEY (id)
    REFERENCES public.candidates (user_id)
    NOT VALID;


ALTER TABLE public.system_personels
    ADD FOREIGN KEY (user_id)
    REFERENCES public.confirmation (system_personel_id)
    NOT VALID;


ALTER TABLE public.employers
    ADD FOREIGN KEY (user_id)
    REFERENCES public.confirmation (employer_id)
    NOT VALID;


ALTER TABLE public.users
    ADD FOREIGN KEY (id)
    REFERENCES public.activation_codes (user_id)
    NOT VALID;

END;